# docker-compose file to manage the LabCAS/Celery/Redis application stack

version: '3.3'

networks: 
  default:
    external: 
      name: labcas-network 

services:

  redis:
    image: redis
    container_name: redis
    # expose port to client running on localhost
    ports:
      - 6379:6379
    # start redis with data persistence
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      # persist redis data
      - redis-data:/data
      
  celery-worker:
    image: edrn/labcas-celery
    user: noroot
    build:
      context: .
    command: ["celery", "-A",  "labcas.celery.worker", "worker", "-l=info"]
    env_file:
      - labcas-celery.env
    restart: always
    depends_on:
      - redis
    
  flower:
    image: edrn/labcas-celery
    container_name: flower
    user: noroot
    ports:
      - 5555:5555
    restart: always
    command: ["celery", "-A",  "labcas.celery.worker", "flower", "-l", "info", "--url_prefix=flower"]
    env_file:
      - labcas-celery.env
    depends_on:
      - redis
      - celery-worker
      
  nginx:
     image: nginx
     # makes flower available at: http://<hostname>:<port>/flower/
     ports:
        - "80:80"
     volumes:
        # override default nginx configuration
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
     depends_on:
       - flower 


volumes:
  redis-data: