# Kubernetes job to run a single iteration of translate_multi_channel_frames_parallel.py
apiVersion: batch/v1
kind: Job
metadata:
  generateName: unmc-
  labels:
    app: labcas-unmc
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: translator
          image: edrn/labcas-celery-unmc-images
          imagePullPolicy: Always
          command:
            - python 
            - -u 
            - translate_multi_channel_frames_parallel.py 
            - /input_data/ 
            - /output_data/
          volumeMounts:
            - name: output-data
              mountPath: /output_data
            - name: input-data
              mountPath: /input_data
          resources:
            requests:
              memory: "60Gi"
              cpu: "4"
            limits:
              memory: "60Gi"
              cpu: "4"
      volumes: 
        - name: input-data
          hostPath:
            #path: /efs-ecs/docker/labcas/edrn/archive/UNMC_Pancreatic_Cancer_MxIF_Images/Primary/UNMCPC.PANC39rf7522
            #path: /efs-ecs/docker/labcas/unmcpc/input_data/2020/
            path: ${INPUT_DATA}
            type: Directory
        - name: output-data
          hostPath:
            #path: /efs-ecs/docker/labcas/edrn/archive/UNMC_Pancreatic_Cancer_MxIF_Images/Primary/UNMCPC.PANC39rf7522_registered_tiff
            #path: /efs-ecs/docker/labcas/unmcpc/output_data/2020/
            path: ${OUTPUT_DATA}
            type: Directory 
        
