# Kubernetes job to run a single iteration of translate_multi_channel_frames_parallel.py
apiVersion: batch/v1
kind: Job
metadata:
  generateName: unmc-
  labels:
    app: labcas-unmc
    exec_date: "${EXEC_DATE}"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: translator
          image: edrn/reg_mult
          imagePullPolicy: Always
          #command: reg_mult
          volumeMounts:
            - name: output-data
              mountPath: /usr/src/app/output
            - name: input-data
              mountPath: /usr/src/app/input
          resources:
            requests:
              memory: "60Gi"
              cpu: "4"
            limits:
              memory: "60Gi"
              cpu: "4"
      volumes: 
        - name: input-data
          hostPath:
            path: ${INPUT_DIR}
            type: Directory
        - name: output-data
          hostPath:
            path: ${OUTPUT_DIR}
            type: Directory
