# docker-compose file that overrides the standard celery worker container
# with the a container equipped with common RNA-Sequencing tools

version: '3.3'

services:

  # LabCAS Celery worker with RNA-Sequencing tools
  celery-worker:
    image: edrn/labcas-celery-rnaseq
    command: ["celery", "-A",  "labcas.celery.worker", "worker", "--loglevel=info", "-Q", "rnaseq", "-n", "rnaseq-worker", "-c", "1"]
    build:
      # context path is relative to location of this docker-compose file
      context: .
    environment:
      RNASEQ_DATA_DIR: /data/rnaseq
    volumes:
      - ${HOME}/data/rnaseq/:/data/rnaseq/
      
  # override flower container to use the image that includes the RNA-Sequencing tasks
  flower:
    image: edrn/labcas-celery-rnaseq
    
      