# Sample information
SAMPLES:
  - "AM00-Ac_1"
  - "AM00-Ac_2"
  - "AM00-Ac_3"
  - "AM00-HG_1"
  - "AM00-HG_2"
  - "AM00-HG_3"
  - "AM00-LG_1"
  - "AM00-LG_2"
  - "AM00-LG_3"
  - "AM00-LG_4"
  - "AM00-LG_5"
  - "AM00-LG_6"
  - "AM00-ND_1"
  - "AM00-ND_2"
  - "AM00-ND_3"
  - "AM00-ND_4"
  - "AM00-ND_5"
  - "AM00-ND_6"
  - "AM129-Ac_1"
  - "AM129-Ac_2"
  - "AM129-Ac_3"
  - "AM129-Ac_4"
  - "AM129-HG_1"
  - "AM129-HG_2"
  - "AM129-HG_3"
  - "AM129-ND_1"
  - "AM129-ND_2"
  - "AM129-ND_4"
  - "AM17-Ac_1"
  - "AM17-Ac_2"
  - "AM17-Ac_3"
  - "AM17-HG_1"
  - "AM17-HG_2"
  - "AM17-HG_3"
  - "AM17-HG_4"
  - "AM17-HG_5"
  - "AM17-HG_6"
  - "AM17-LG_1"
  - "AM17-LG_2"
  - "AM17-LG_3"
  - "AM17-LG_4"
  - "AM17-LG_5"
  - "AM17-LG_6"
  - "AM17-ND_4"
  - "AM17-ND_5"
  - "AM17-ND_6"
  - "AM33-HG_1"
  - "AM33-HG_2"
  - "AM33-HG_3"
  - "AM33-LG_1"
  - "AM33-LG_2"
  - "AM33-LG_3"
  - "AM33-ND_1"
  - "AM33-ND_2"
  - "AM33-ND_3"
  - "AM77-HG_1"
  - "AM77-HG_2"
  - "AM77-HG_3"
  - "AM77-LG_1"
  - "AM77-LG_2"
  - "AM77-LG_3"
  - "AM77-LG_4"
  - "AM77-LG_5"
  - "AM77-LG_6"
  - "AM92-Ac_1"
  - "AM92-Ac_2"
  - "AM92-Ac_3"
  - "AM92-HG_1"
  - "AM92-HG_2"
  - "AM92-HG_3"
  - "AM92-LG_1"
  - "AM92-LG_2"
  - "AM92-LG_3"
  - "AM92-LG_4"
  - "AM92-LG_5"
  - "AM92-LG_6"
  - "AM92-ND_1"
  - "AM92-ND_2"
  - "AM92-ND_3"
  - "AM98-Ac_1"
  - "AM98-Ac_2"
  - "AM98-Ac_3"
  - "AM98-HG_1"
  - "AM98-HG_2"
  - "AM98-HG_3"
  - "AM98-LG_1"
  - "AM98-LG_2"
  - "AM98-LG_3"
  - "AM98-ND_1"
  - "AM98-ND_2"
  - "AM98-ND_3"
  - "AM98-ND_4"
  - "AM98-ND_5"
  - "AM98-ND_6"
  - "IN01-HG_1"
  - "IN01-HG_2"
  - "IN02-HG_1"
  - "IN02-LG_1"
  - "IN02-LG_2"
  - "IN04-Ac_1"
  - "IN04-Ac_2"
  - "IN04-Ac_3"
  - "IN04-HG_1"
  - "IN04-HG_2"
  - "IN04-HG_3"
  - "IN04-HG_4"
  - "IN04-HG_5"
  - "IN04-HG_6"
  - "IN04-ND_1"
  - "IN04-ND_2"
  - "IN04-ND_3"
  - "MK112-Ac_1"
  - "MK112-Ac_2"
  - "MK112-Ac_3"
  - "MK112-HG_1"
  - "MK112-HG_2"
  - "MK112-HG_3"
  - "MK112-LG_1"
  - "MK112-LG_2"
  - "MK112-LG_3"
  - "MK112-ND_1"
  - "MK112-ND_2"
  - "MK112-ND_3"
  - "MK124-Ac_1"
  - "MK124-Ac_2"
  - "MK124-Ac_3"
  - "MK124-HG_1"
  - "MK124-HG_2"
  - "MK124-HG_3"
  - "MK124-ND_1"
  - "MK124-ND_2"
  - "MK124-ND_3"
  - "MK257-HG_1"
  - "MK257-HG_2"
  - "MK257-HG_3"
  - "MK310-HG_1"
  - "MK310-HG_2"
  - "MK310-HG_3"
  - "MK310-LG_1"
  - "MK310-LG_2"
  - "MK310-LG_3"
  - "MK311-Ac_1"
  - "MK311-Ac_2"
  - "MK311-Ac_4"
  - "MK311-HG_1"
  - "MK311-HG_2"
  - "MK311-HG_3"
  - "MK311-ND_1"
  - "MK311-ND_2"
  - "MK311-ND_3"
  - "MK311-ND_4"
  - "MK311-PDAC_1"
  - "MK311-PDAC_2"
  - "MK311-PDAC_3"
  - "MK311-PDAC_4"
  - "MK311-PDAC_5"
  - "MK311-PDAC_6"
  - "MK328-HG_1"
  - "MK328-HG_2"
  - "MK328-HG_3"
  - "MK328-LG_1"
  - "MK328-LG_2"
  - "MK328-LG_3"
  - "MK74-HG_1"
  - "MK74-HG_2"
  - "MK74-HG_3"
  - "MK74-LG_1"
  - "MK74-LG_2"
  - "MK74-LG_3"
  - "MK74-ND_1"
  - "MK74-ND_2"
  - "MK74-PDAC_1"
  - "MK74-PDAC_2"
  - "MK74-PDAC_3"
  - "UCSD204-HG_1"
  - "UCSD204-HG_2"
  - "UCSD204-HG_3"
  - "UCSD204-LG_1"
  - "UCSD204-LG_2"
  - "UCSD204-LG_3"
  - "UCSD205-Ac_1"
  - "UCSD205-Ac_2"
  - "UCSD205-Ac_3"
  - "UCSD205-HG_1"
  - "UCSD205-HG_2"
  - "UCSD205-HG_3"
  - "UCSD205-LG_1"
  - "UCSD205-LG_2"
  - "UCSD205-LG_3"
  - "UCSD205-ND_1"
  - "UCSD205-ND_2"
  - "UCSD205-ND_3"
  - "UCSD206-HG_1"
  - "UCSD206-HG_2"
  - "UCSD206-HG_3"
  - "UCSD206-HG_4"
  - "UCSD206-HG_5"
  - "UCSD206-HG_6"
  - "UCSD206-LG_1"
  - "UCSD206-LG_2"
  - "UCSD206-LG_3"
  - "UCSD206-ND_1"
  - "UCSD206-ND_2"
  - "UCSD206-ND_3"
  - "UCSD206-ND_4"
  - "UCSD206-ND_5"
  - "UCSD206-ND_6"
  - "UCSD207-Ac_1"
  - "UCSD207-Ac_2"
  - "UCSD207-Ac_3"
  - "UCSD207-Ac_4"
  - "UCSD207-Ac_5"
  - "UCSD207-Ac_6"
  - "UCSD207-HG_1"
  - "UCSD207-HG_2"
  - "UCSD207-HG_3"
  - "UCSD207-HG_4"
  - "UCSD207-HG_5"
  - "UCSD207-HG_6"
  - "UCSD207-LG_1"
  - "UCSD207-LG_2"
  - "UCSD207-LG_3"
  - "UCSD207-LG_4"
  - "UCSD207-LG_5"
  - "UCSD207-LG_6"
  - "UCSD207-ND_1"
  - "UCSD207-ND_2"
  - "UCSD207-ND_3"
  - "UCSD207-ND_4"
  - "UCSD207-ND_5"
  - "UCSD207-ND_6"
  - "UT01-HG_1"
  - "UT01-HG_2"
  - "UT01-HG_3"
  - "UT01-HG_4"
  - "UT01-LG_1"
  - "UT01-LG_2"
  - "UT01-LG_3"
  - "UT01-LG_4"
  - "UT01-ND_1"
  - "UT01-ND_2"
  - "UT01-ND_3"
  - "UT01-ND_4"
  - "UT02-HG_1"
  - "UT02-HG_2"
  - "UT02-HG_3"
  - "UT02-LG_1"
  - "UT02-LG_2"
  - "UT02-LG_3"
  - "UT02-ND_1"
  - "UT02-ND_2"
  - "UT02-ND_3"

# Read group names to use in bam files
RG_NAME: "MCL-SMART3SEQ"

# Adapter sequences
ADAPTER_3_PRIME: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
ADAPTER_5_PRIME: "ATCTCGTATGCCGTCTTCTGCTTG"

# 3SEQ-tools parameters
N: "5"  # Length of UMI
G: "3"  # Length of G-overhang
A: "8"  # Minimum length of homopolymer detection
M: "1"  # Number of mismatches allowed

# Other parameters
ML: "5" # Minimum length read after adapter trimming

# Reference info
REF_GENOME: "/star_ref/GRCh38.primary_assembly.genome.fa"
GTF: "/star_ref/gencode.v26.primary_assembly.annotation.gtf"
STAR_DIR: "/star_ref"
TEMP_DIR: "/star_ref/_STARtmp"

# Software
THREE_SEQ: "./3SEQtools"
UMI_TOOLS: "./umi-dedup"

# CPU information
RAM: "2000000000"

# Project directory, must exist
PROJECT_DIR: "/project"

# Fastq directory which contains fastq.gz files corresponding to SAMPLES
FASTQ_DIR: "/project/fastq"
