# docker-compose file that overrides 
# the standard celery worker container
# with the tensorflow-enabled worker

version: '3.3'

services:

  # LabCAS Celery worker with Tensorflow package
  celery-worker:
    image: edrn/labcas-celery-tensorflow
    build:
      # context path is relative to location of this docker-compose file
      context: .
    volumes:
      - tensorflow_data:/tmp/tensorflow/mnist/input_data
      
  # override flower container to use the image that includes the Tensorflow tasks
  flower:
    image: edrn/labcas-celery-tensorflow
      
  # init container downloads the tensorflow data to a shared volume
  data-download:
    image: busybox
    container_name: data-download
    entrypoint: /usr/local/bin/data_download.sh
    environment: 
      - TENSORFLOW_DATA=/data
    volumes:
      - ./tensorflow/data_download.sh:/usr/local/bin/data_download.sh
      - tensorflow_data:/data
      
volumes:
  tensorflow_data:
 
