# Manfest file for flower application

apiVersion: v1
kind: Service
metadata:
  name: flower
  labels:
    stack: labcas
    app: flower
spec:
  ports:
    - port: 5555
  selector:
    stack: labcas
    app: flower
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  labels:
    stack: labcas
    app: flower
spec:
  selector:
    matchLabels:
      stack: labcas
      app: flower
  template:
    metadata:
      labels:
        stack: labcas
        app: flower
    spec:
      containers:
      - image: edrn/labcas-celery
        name: flower
        command: ["celery"]
        args: ["-A",  "labcas.celery.worker", "flower", "-l", "info", "--url_prefix=flower", "-c", "10"]
        env:
          - name: CELERY_BROKER_URL
            value: redis://redis:6379/0
          - name: CELERY_BACKEND_URL
            value: redis://redis:6379/0
        ports: 
        - containerPort: 5555
          name: flower
      restartPolicy: Always
