# Manifest file for base Celery worker application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    stack: labcas
    app: worker
spec:
  selector:
    matchLabels:
      stack: labcas
      app: worker
  template:
    metadata:
      labels:
        stack: labcas
        app: worker
    spec:
      containers:
      - image: edrn/labcas-celery
        name: worker
        command: ["celery"]
        args: ["-A",  "labcas.celery.worker", "worker", "-l=info", "-c", "10"]
        env:
          - name: CELERY_BROKER_URL
            value: redis://redis:6379/0
          - name: CELERY_BACKEND_URL
            value: redis://redis:6379/0
      restartPolicy: Always
