# Kubernetes job to run a single iteration of translate_multi_channel_frames_parallel.py
apiVersion: batch/v1
kind: Job
metadata:
  generateName: unmc-
  labels:
    app: labcas-unmc
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: translator
          image: edrn/labcas-celery-unmc-images
          imagePullPolicy: Always
          command:
            - python 
            - -u 
            - translate_multi_channel_frames_parallel.py 
            - /input_data/ 
            - /output_data/
          volumeMounts:
            - name: output-data
              mountPath: /output_data
            - name: input-data
              mountPath: /input_data
          resources:
            requests:
              memory: "32Gi"
              cpu: "4"
            limits:
              memory: "32Gi"
              cpu: "4"
      volumes: 
        - name: output-data
          hostPath:
            #path: /efs-ecs/docker/labcas/UNMC_Test_Data/registered_tiff
            #path: /efs-ecs/docker/labcas/edrn/archive/UNMC_Pancreatic_Cancer_MxIF_Images/Liver/UNMCPC.Liver86rf3504_registered_tiff
            #path: /efs-ecs/docker/labcas/edrn/archive/UNMC_Pancreatic_Cancer_MxIF_Images/Primary/UNMCPC.PANC112rf4530_registered_tiff
            #path: /efs-ecs/docker/labcas/edrn/archive/UNMC_Pancreatic_Cancer_MxIF_Images/Primary/UNMCPC.PANC39rf7522_registered_tiff
            path: /efs-ecs/docker/labcas/unmcpc/Liver/UNMCPC.Liver86rf3504/
            type: Directory 
        - name: input-data
          hostPath:
            #path: /efs-ecs/docker/labcas/UNMC_Test_Data/tiff
            #path: /efs-ecs/docker/labcas/edrn/archive/UNMC_Pancreatic_Cancer_MxIF_Images/Liver/UNMCPC.Liver86rf3504
            #path: /efs-ecs/docker/labcas/edrn/archive/UNMC_Pancreatic_Cancer_MxIF_Images/Primary/UNMCPC.PANC112rf4530
            #path: /efs-ecs/docker/labcas/edrn/archive/UNMC_Pancreatic_Cancer_MxIF_Images/Primary/UNMCPC.PANC39rf7522
            path:/efs-ecs/docker/labcas/unmcpc/Liver/UNMCPC.Liver86rf3504_registered_tiff/
            type: Directory
